// Curated static list of major Israeli cities for the profile "city" field
// (self-reported, independent of institutions.city). The stored value IS the
// Hebrew name — same convention as institutions.city — so existing rows,
// seed data and the dropdown all agree.
export const ISRAELI_CITIES = [
  "תל אביב",
  "ירושלים",
  "חיפה",
  "ראשון לציון",
  "פתח תקווה",
  "אשדוד",
  "נתניה",
  "באר שבע",
  "בני ברק",
  "חולון",
  "רמת גן",
  "בת ים",
  "רחובות",
  "אשקלון",
  "הרצליה",
  "כפר סבא",
  "חדרה",
  "מודיעין",
  "רעננה",
  "נצרת",
  "לוד",
  "רמלה",
  "גבעתיים",
  "הוד השרון",
  "אילת",
  "קרית גת",
  "עפולה",
  "טבריה",
  "נהריה",
  "יבנה",
] as const;
